
services:
  api:
    build: .
    container_name: deploy_python
    env_file: .env
    ports:
      - "8000:8000" 
    depends_on:
      - db    # Garantir que o banco de dados inicie antes da API
    volumes:
      - .:/app    # Monta o diretório atual no contêiner para desenvolvimento
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Persistência de dados
  
volumes:
    db_data:
